// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunWritesExpectedLocalOutputs(t *testing.T) {
	tmp := t.TempDir()

	writeTestFile(t, filepath.Join(tmp, "imports.yaml"), `imports:
  - path: app
    repo: https://example.com/app.git
`)

	writeTestFile(t, filepath.Join(tmp, "app", "go.mod"), `module example.com/app

go 1.22

require github.com/pkg/errors v0.9.1
`)
	writeTestFile(t, filepath.Join(tmp, "app", "vendor", "modules.txt"), `# github.com/pkg/errors v0.9.1
## explicit
`)
	writeTestFile(t, filepath.Join(tmp, "app", "vendor", "github.com", "pkg", "errors", "LICENSE"), "BSD 2-Clause License\n")

	writeTestFile(t, filepath.Join(tmp, "app", "Cargo.toml"), `[dependencies]
serde = "1"
serde_json = { version = "1.0" }
`)

	writeTestFile(t, filepath.Join(tmp, "app", "pyproject.toml"), `[project]
dependencies = ["Requests>=2.0"]

[project.optional-dependencies]
dev = ["PyYAML==6.0"]
`)
	writeTestFile(t, filepath.Join(tmp, "app", "pnpm-lock.yaml"), `lockfileVersion: '9.0'
packages:
  '@scope/example@1.2.3(peer@4.5.6)':
    resolution: {integrity: sha512-example}
`)

	// Project POMs are intentionally ignored. Java dependency discovery uses
	// the component descriptor and its Bazel-generated runtime inventory.
	writeTestFile(t, filepath.Join(tmp, "app", "pom.xml"), `<project>
  <modelVersion>4.0.0</modelVersion>
  <dependencies>
    <dependency>
      <groupId>org.example</groupId>
      <artifactId>ignored-project-pom</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>
`)
	javaComponent := filepath.Join(tmp, "src", "control-plane-services", "demo")
	writeTestFile(t, filepath.Join(javaComponent, javaDescriptorName), `{
  "ci_lane": "build-container",
  "component_kind": "java-service",
  "id": "demo",
  "tests_skip": false
}
`)
	javaInventoryRoot := filepath.Join(tmp, "bazel-bin")
	// Use a synthetic resolved coordinate so this fixture never constrains or
	// implies a production dependency version.
	writeTestFile(
		t,
		filepath.Join(
			javaInventoryRoot,
			"src",
			"control-plane-services",
			"demo",
			"runtime_inventory.json",
		),
		`{
  "dependencies": [
    {
      "coordinate": "org.example:sample-runtime-library:1.2.3",
      "licenses": ["Apache-2.0"],
      "name": "Sample Runtime Library",
      "url": "https://example.invalid/sample-runtime-library"
    }
  ]
}
`,
	)

	writeTestFile(t, filepath.Join(tmp, "app", "Chart.yaml"), `apiVersion: v2
name: app
version: 0.1.0
dependencies:
  - name: chart-from-yaml
    version: 1.0.0
    repository: https://charts.example.com
`)
	writeTestFile(t, filepath.Join(tmp, "app", "Chart.lock"), `dependencies:
  - name: chart-from-lock
    version: 2.0.0
    repository: https://charts.example.com
`)
	writeTestFile(t, filepath.Join(tmp, "dependencies-java.md"), "manual-java-snapshot\n")

	t.Setenv("REPO_ROOT", tmp)
	t.Setenv("COLLECT_DEPS_NO_PYPI", "1")
	t.Setenv("COLLECT_DEPS_NO_NPM", "1")
	t.Setenv("COLLECT_DEPS_NO_CRATES_IO", "1")
	t.Setenv("COLLECT_DEPS_NO_HELM_SHOW", "1")
	t.Setenv("COLLECT_DEPS_NO_GITHUB", "1")
	t.Setenv("COLLECT_DEPS_NO_GO_LIST", "1")
	t.Setenv("COLLECT_DEPS_NO_GO_MOD_DOWNLOAD", "1")
	t.Setenv("COLLECT_DEPS_JAVA_INVENTORY_ROOT", javaInventoryRoot)

	oldArgs := os.Args
	t.Cleanup(func() { os.Args = oldArgs })
	os.Args = []string{"collect-dependencies", "--language", "all"}

	resetGlobalsForTest()
	if err := run(); err != nil {
		t.Fatalf("run failed: %v", err)
	}

	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "Generated by `go run -C ./tools/collect-dependencies .`.")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "See [`tools/collect-dependencies/README.md`](tools/collect-dependencies/README.md) for license caveats.")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "## BSD-2-Clause")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Go`: `github.com/pkg/errors`")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "## Unresolved")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Rust`: `serde 1` - _(no license resolved - install `cargo` for `cargo metadata`, or allow crates.io fallback; see tools/collect-dependencies/README.md)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Rust`: `serde_json 1.0` - _(no license resolved - install `cargo` for `cargo metadata`, or allow crates.io fallback; see tools/collect-dependencies/README.md)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Python`: `PyYAML==6.0` - _(PyPI lookup disabled)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Python`: `Requests>=2.0` - _(PyPI lookup disabled)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Node.js`: `@scope/example@1.2.3` - _(npm registry lookup disabled)_")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Java`: `org.example:sample-runtime-library:1.2.3` (Sample Runtime Library; https://example.invalid/sample-runtime-library)")
	assertFileNotContains(t, filepath.Join(tmp, "dependencies.md"), "ignored-project-pom")
	assertFileContains(t, filepath.Join(tmp, "dependencies.md"), "- `Helm`: `chart-from-lock 2.0.0 @ https://charts.example.com` - _(no license resolved - set `COLLECT_DEPS_NO_HELM_SHOW=1` to skip `helm show chart`, or provide chart metadata / source repo license hints)_")

	assertFileEquals(t, filepath.Join(tmp, "dependencies-java.md"), "manual-java-snapshot\n")
	assertFileNotContains(t, filepath.Join(tmp, "dependencies.md"), "chart-from-yaml")
	assertFileMissing(t, filepath.Join(tmp, "dependencies-go.md"))
	assertFileMissing(t, filepath.Join(tmp, "dependencies-rust.md"))
	assertFileMissing(t, filepath.Join(tmp, "dependencies-python.md"))
	assertFileMissing(t, filepath.Join(tmp, "dependencies-helm.md"))
}

func TestNormalizeLicenseGroupKeepsMPLVersion(t *testing.T) {
	if got := normalizeLicenseGroup("Mozilla Public License 1.1"); got != "MPL-1.1" {
		t.Fatalf("normalizeLicenseGroup returned %q, want MPL-1.1", got)
	}
	if got := normalizeLicenseGroup("MPL 2.0"); got != "MPL-2.0" {
		t.Fatalf("normalizeLicenseGroup returned %q, want MPL-2.0", got)
	}
}

func TestParsePNPMLockUsesResolvedPackageVersions(t *testing.T) {
	tmp := t.TempDir()
	path := filepath.Join(tmp, "pnpm-lock.yaml")
	writeTestFile(t, path, `lockfileVersion: '9.0'
packages:
  '@scope/example@1.2.3(peer@4.5.6)':
    resolution: {integrity: sha512-example}
  unscoped@7.8.9:
    resolution: {integrity: sha512-example}
  file:../workspace:
    resolution: {directory: ../workspace}
  'linked@link:../workspace':
    resolution: {directory: ../workspace}
`)

	got, err := parsePNPMLock(path)
	if err != nil {
		t.Fatalf("parsePNPMLock returned error: %v", err)
	}
	for _, want := range []string{"@scope/example@1.2.3", "unscoped@7.8.9"} {
		if _, ok := got[want]; !ok {
			t.Fatalf("parsePNPMLock missing %q from %#v", want, got)
		}
	}
	for _, local := range []string{"file:../workspace", "linked@link:../workspace"} {
		if _, ok := got[local]; ok {
			t.Fatalf("parsePNPMLock included local dependency %q in %#v", local, got)
		}
	}
	if len(got) != 2 {
		t.Fatalf("parsePNPMLock returned %d dependencies, want 2: %#v", len(got), got)
	}
}

func TestRunFailsOnInvalidPNPMLock(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "imports.yaml"), `imports:
  - path: app
    repo: https://example.com/app.git
`)
	writeTestFile(t, filepath.Join(tmp, "app", "pnpm-lock.yaml"), "packages: [\n")

	t.Setenv("REPO_ROOT", tmp)
	oldArgs := os.Args
	t.Cleanup(func() { os.Args = oldArgs })
	os.Args = []string{"collect-dependencies", "--language", "node"}

	resetGlobalsForTest()
	if err := run(); err == nil {
		t.Fatal("expected invalid pnpm lockfile error")
	}
}

func TestParseCargoTOMLResolvesWorkspaceDependencyVersions(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "Cargo.toml"), `[workspace]
members = ["crates/app"]

[workspace.dependencies]
anyhow = "=1.0.102"
serde = { version = "1.0", features = ["derive"] }
internal = { path = "crates/internal" }
`)
	writeTestFile(t, filepath.Join(tmp, "crates", "app", "Cargo.toml"), `[package]
name = "app"
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
internal = { workspace = true }
local-only = { path = "../local-only" }
`)

	got := parseCargoTOML(filepath.Join(tmp, "crates", "app", "Cargo.toml"))
	for _, want := range []string{"anyhow =1.0.102", "serde 1.0", "internal", "local-only"} {
		if _, ok := got[want]; !ok {
			t.Fatalf("parseCargoTOML missing %q from %#v", want, got)
		}
	}
}

func TestParseCargoTOMLStopsAtPathOnlyWorkspaceRoot(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "Cargo.toml"), `[workspace]
members = ["repo"]

[workspace.dependencies]
internal = "=9.9.9"
`)
	writeTestFile(t, filepath.Join(tmp, "repo", "Cargo.toml"), `[workspace]
members = ["crates/app"]

[workspace.dependencies]
internal = { path = "crates/internal" }
`)
	writeTestFile(t, filepath.Join(tmp, "repo", "crates", "app", "Cargo.toml"), `[package]
name = "app"
version = "0.1.0"

[dependencies]
internal = { workspace = true }
`)

	got := parseCargoTOML(filepath.Join(tmp, "repo", "crates", "app", "Cargo.toml"))
	if _, ok := got["internal"]; !ok {
		t.Fatalf("parseCargoTOML missing path-only workspace dep from %#v", got)
	}
	if _, ok := got["internal =9.9.9"]; ok {
		t.Fatalf("parseCargoTOML used ancestor workspace dep version: %#v", got)
	}
}

func TestLicenseFromPlainDirSkipsNonLicenseFallbackText(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "LICENSE"), "Permalink:\nhttps://example.com/license\n")

	if got := licenseFromPlainDir(tmp); got != "" {
		t.Fatalf("licenseFromPlainDir returned %q, want empty string", got)
	}
}

func TestLicenseFromPlainDirKeepsLicenseLikeFallbackText(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "LICENSE"), "BSD 2-Clause License\n")

	if got := licenseFromPlainDir(tmp); got != "BSD-2-Clause" {
		t.Fatalf("licenseFromPlainDir returned %q, want BSD-2-Clause", got)
	}
}

func TestImportPathsFromManifestIncludesNativeRoots(t *testing.T) {
	tmp := t.TempDir()
	repoRoot = tmp

	writeTestFile(t, filepath.Join(tmp, "imports.yaml"), `imports:
  - path: src/libraries/go/lib
    authoritative_source: native
  - path: src/services/demo
    repo: https://example.com/demo.git
    commit: deadbeef
`)

	got, err := importPathsFromManifest(filepath.Join(tmp, "imports.yaml"))
	if err != nil {
		t.Fatalf("importPathsFromManifest failed: %v", err)
	}

	want := []string{
		filepath.Join(tmp, "src/libraries/go/lib"),
		filepath.Join(tmp, "src/services/demo"),
	}
	if len(got) != len(want) {
		t.Fatalf("importPathsFromManifest returned %d paths, want %d (%v)", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("importPathsFromManifest path[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

func TestRunWithoutImportsScansNativeRepository(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(t, filepath.Join(tmp, "go.mod"), `module example.com/native

go 1.26

require github.com/pkg/errors v0.9.1
`)
	t.Setenv("REPO_ROOT", tmp)
	t.Setenv("COLLECT_DEPS_NO_GO_LIST", "1")
	t.Setenv("COLLECT_DEPS_NO_GO_MOD_DOWNLOAD", "1")
	t.Setenv("COLLECT_DEPS_NO_GITHUB", "1")

	oldArgs := os.Args
	t.Cleanup(func() { os.Args = oldArgs })
	os.Args = []string{"collect-dependencies", "--language", "go"}

	resetGlobalsForTest()
	if err := run(); err != nil {
		t.Fatalf("run failed: %v", err)
	}
	assertFileContains(
		t,
		filepath.Join(tmp, "dependencies.md"),
		"- `Go`: `github.com/pkg/errors`",
	)
}

func TestGoListLicenseEnrichmentDoesNotModifyModuleFiles(t *testing.T) {
	tmp := t.TempDir()
	moduleFile := filepath.Join(tmp, "go.mod")
	writeTestFile(t, moduleFile, `module example.com/app

go 1.26

require example.com/dep v0.0.0

replace example.com/dep => ./dep
`)
	writeTestFile(t, filepath.Join(tmp, "dep", "go.mod"), `module example.com/dep

go 1.26
`)
	writeTestFile(t, filepath.Join(tmp, "dep", "LICENSE"), "BSD 2-Clause License\n")

	before, err := os.ReadFile(moduleFile)
	if err != nil {
		t.Fatal(err)
	}
	allModules := map[string]struct{}{"example.com/dep": {}}
	licenses := map[string]map[string]struct{}{}
	enrichGoLicensesFromGoModuleList(allModules, licenses, []string{tmp})

	if got := formatGoLicense(licenses, "example.com/dep"); got != "BSD-2-Clause" {
		t.Fatalf("Go license = %q, want BSD-2-Clause", got)
	}
	after, err := os.ReadFile(moduleFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(after) != string(before) {
		t.Fatalf("go.mod changed during read-only license enrichment")
	}
	if _, err := os.Stat(filepath.Join(tmp, "go.sum")); !os.IsNotExist(err) {
		t.Fatalf("go.sum was created during read-only license enrichment: %v", err)
	}
}

func TestJavaRuntimeInventoriesMergeUsedDependencies(t *testing.T) {
	tmp := t.TempDir()
	inventoryRoot := filepath.Join(tmp, "bazel-bin")
	for _, component := range []string{"alpha", "beta"} {
		writeJavaDescriptor(
			t,
			filepath.Join(tmp, "src", "control-plane-services", component),
			component,
		)
	}
	writeJavaInventory(
		t,
		filepath.Join(
			inventoryRoot,
			"src",
			"control-plane-services",
			"alpha",
			"runtime_inventory.json",
		),
		`[
  {
    "coordinate": "org.example:shared:1.0",
    "licenses": ["Apache-2.0"],
    "name": "Shared",
    "url": "https://example.com/shared"
  },
  {
    "coordinate": "org.example:alpha-only:2.0",
    "licenses": ["MIT"],
    "name": "Alpha",
    "url": "https://example.com/alpha"
  }
]`,
	)
	writeJavaInventory(
		t,
		filepath.Join(
			inventoryRoot,
			"src",
			"control-plane-services",
			"beta",
			"runtime_inventory.json",
		),
		`[
  {
    "coordinate": "org.example:shared:1.0",
    "licenses": ["Apache-2.0"],
    "name": "Shared",
    "url": "https://example.com/shared"
  }
]`,
	)
	t.Setenv("COLLECT_DEPS_JAVA_INVENTORY_ROOT", inventoryRoot)

	dependencies, componentCount, err := collectJavaInventoryDependencies(tmp)
	if err != nil {
		t.Fatalf("collectJavaInventoryDependencies failed: %v", err)
	}
	if componentCount != 2 {
		t.Fatalf("component count = %d, want 2", componentCount)
	}
	if len(dependencies) != 2 {
		t.Fatalf("dependency count = %d, want 2: %#v", len(dependencies), dependencies)
	}
	if _, ok := dependencies["org.example:shared:1.0"]; !ok {
		t.Fatalf("shared dependency missing from %#v", dependencies)
	}
	if _, ok := dependencies["org.example:alpha-only:2.0"]; !ok {
		t.Fatalf("service-only dependency missing from %#v", dependencies)
	}
	if _, ok := dependencies["org.example:hub-only:9.9"]; ok {
		t.Fatalf("unused hub dependency unexpectedly present in %#v", dependencies)
	}
}

func TestDiscoverJavaComponentsRejectsMalformedDescriptor(t *testing.T) {
	tmp := t.TempDir()
	writeTestFile(
		t,
		filepath.Join(tmp, "src", "control-plane-services", "demo", javaDescriptorName),
		`{
  "ci_lane": "build-container",
  "component_kind": "java-service",
  "id": "demo"
}
`,
	)

	_, err := discoverJavaComponents(tmp)
	if err == nil || !strings.Contains(err.Error(), "tests_skip") {
		t.Fatalf("expected missing tests_skip error, got %v", err)
	}
}

func TestCollectJavaDependenciesRejectsMissingInventory(t *testing.T) {
	tmp := t.TempDir()
	writeJavaDescriptor(
		t,
		filepath.Join(tmp, "src", "control-plane-services", "demo"),
		"demo",
	)
	t.Setenv("COLLECT_DEPS_JAVA_INVENTORY_ROOT", filepath.Join(tmp, "bazel-bin"))

	_, _, err := collectJavaInventoryDependencies(tmp)
	if err == nil || !strings.Contains(err.Error(), "runtime_inventory.json") {
		t.Fatalf("expected missing inventory error, got %v", err)
	}
}

func TestMaterializeJavaInventoriesReportsMissingTarget(t *testing.T) {
	tmp := t.TempDir()
	fakeBazel := filepath.Join(tmp, "fake-bazel")
	writeTestFile(t, fakeBazel, `#!/bin/sh
echo "ERROR: no such target '//src/control-plane-services/demo:runtime_inventory.json'" >&2
exit 1
`)
	if err := os.Chmod(fakeBazel, 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("COLLECT_DEPS_BAZEL", fakeBazel)
	t.Setenv("BAZEL_OUTPUT_USER_ROOT", "")

	component := javaComponent{
		ID:     "demo",
		Path:   "src/control-plane-services/demo",
		Target: "//src/control-plane-services/demo:runtime_inventory.json",
	}
	_, err := materializeJavaInventories(tmp, []javaComponent{component})
	if err == nil {
		t.Fatal("expected missing target error")
	}
	for _, want := range []string{"no such target", component.Target} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("error %q does not contain %q", err, want)
		}
	}
}

func writeJavaDescriptor(t *testing.T, directory, id string) {
	t.Helper()
	writeTestFile(
		t,
		filepath.Join(directory, javaDescriptorName),
		fmt.Sprintf(`{
  "ci_lane": "build-container",
  "component_kind": "java-service",
  "id": %q,
  "tests_skip": false
}
`, id),
	)
}

func writeJavaInventory(t *testing.T, path, dependencies string) {
	t.Helper()
	writeTestFile(
		t,
		path,
		fmt.Sprintf(`{
  "dependencies": %s
}
`, dependencies),
	)
}

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func assertFileContains(t *testing.T, path, needle string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if !strings.Contains(string(raw), needle) {
		t.Fatalf("%s does not contain %q\n%s", path, needle, string(raw))
	}
}

func assertFileNotContains(t *testing.T, path, needle string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if strings.Contains(string(raw), needle) {
		t.Fatalf("%s unexpectedly contains %q\n%s", path, needle, string(raw))
	}
}

func assertFileMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("expected %s to be missing, got err=%v", path, err)
	}
}

func assertFileEquals(t *testing.T, path, want string) {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if string(raw) != want {
		t.Fatalf("%s content mismatch\nwant:\n%s\ngot:\n%s", path, want, string(raw))
	}
}

func resetGlobalsForTest() {
	repoRoot = ""
	cargoMissingLogged = false
	githubLicenseWarned = false
	githubAuthLogged = false
	goListHintLogged = false
	goModDownloadHintLogged = false
	helmMissingLogged = false
}

func TestImportPathsFromManifestMissingReturnsRepositoryRoot(t *testing.T) {
	// On the OSS mirror imports.yaml is intentionally absent, so native
	// dependency discovery scans the repository root.
	tmp := t.TempDir()
	repoRoot = tmp
	got, err := importPathsFromManifest(filepath.Join(tmp, "imports.yaml"))
	if err != nil {
		t.Fatalf("expected no error for missing imports.yaml, got %v", err)
	}
	if len(got) != 1 || got[0] != tmp {
		t.Fatalf("expected repository root %q, got %v", tmp, got)
	}
}
