// SPDX-FileCopyrightText: Copyright (c) NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	parsed, err := parseArgs(os.Args[1:])
	if err != nil {
		return err
	}

	repoRoot, err = findRepoRoot()
	if err != nil {
		return err
	}

	requestedLangs := requestedLanguages(parsed.Language)
	langs := map[string]bool{}
	for lang := range requestedLangs {
		langs[lang] = true
	}

	manifestPath := filepath.Join(repoRoot, "imports.yaml")
	importRoots, err := importPathsFromManifest(manifestPath)
	if err != nil {
		return err
	}
	if len(importRoots) == 0 {
		return fmt.Errorf("no dependency scan roots discovered from %s", manifestPath)
	}

	all := dependencyScan{
		Go:     map[string]struct{}{},
		Rust:   map[string]struct{}{},
		Python: map[string]struct{}{},
		Node:   map[string]struct{}{},
		Helm:   map[string]struct{}{},
	}

	for _, root := range importRoots {
		if st, err := os.Stat(root); err != nil || !st.IsDir() {
			if err == nil {
				err = fmt.Errorf("not a directory")
			}
			return fmt.Errorf("dependency scan root %s: %w", root, err)
		}
		scan, err := scanTree(root, langs)
		if err != nil {
			return err
		}
		mergeSet(all.Go, scan.Go)
		mergeSet(all.Rust, scan.Rust)
		mergeSet(all.Python, scan.Python)
		mergeSet(all.Node, scan.Node)
	}

	if langs["helm"] {
		helmDeps, err := collectHelmDependencies(importRoots)
		if err != nil {
			return err
		}
		mergeSet(all.Helm, helmDeps)
	}

	goLicenses := map[string]map[string]struct{}{}
	if langs["go"] {
		maybeVendorGoModules(importRoots)
		for _, root := range importRoots {
			mergeLicenseMap(goLicenses, collectGoLicensesFromVendor(root))
		}
		goModuleDirs := findGoModuleDirs(importRoots)
		enrichGoLicensesFromGoModuleList(all.Go, goLicenses, goModuleDirs)
		enrichGoLicensesFromGoModDownload(all.Go, goLicenses, goModuleDirs)
		enrichGoLicensesFromGitHub(all.Go, goLicenses)
	}

	rustLicenses := map[string]map[string]struct{}{}
	if langs["rust"] {
		rustLicenses = collectRustLicenses(importRoots)
		if !envBool("COLLECT_DEPS_NO_CRATES_IO") {
			cratesCache := map[string]*string{}
			for _, stem := range sortedCrateStems(all.Rust) {
				if rustLicenseForCrate(rustLicenses, stem) != nil {
					continue
				}
				if lic := cratesIOLicense(stem, cratesCache); lic != "" {
					for _, key := range rustNameKeys(stem) {
						addLicense(rustLicenses, key, lic)
					}
				}
			}
		}
	}

	usePyPI := langs["python"] && !envBool("COLLECT_DEPS_NO_PYPI")
	pypiCache := map[string]*string{}
	useNPM := langs["node"] && !envBool("COLLECT_DEPS_NO_NPM")
	npmCache := map[string]*string{}

	javaDependencies := map[string]mergedJavaDependency{}
	javaComponentCount := 0
	if langs["java"] {
		javaDependencies, javaComponentCount, err = collectJavaInventoryDependencies(repoRoot)
		if err != nil {
			return err
		}
	}

	helmLicenses := map[string]map[string]struct{}{}
	if langs["helm"] {
		helmLicenses = collectHelmLicenses(all.Helm)
	}

	header := "Generated by `go run -C ./tools/collect-dependencies .`. Refresh: `go run -C ./tools/collect-dependencies .`. See [`tools/collect-dependencies/README.md`](tools/collect-dependencies/README.md) for license caveats.\n\n"

	summary := []string{}
	rows := []dependencyRow{}
	rowSummary := []string{}
	if langs["go"] {
		languageRows := buildGoRows(all.Go, goLicenses)
		rows = append(rows, languageRows...)
		rowSummary = append(rowSummary, fmt.Sprintf("Go %d modules", len(languageRows)))
	}

	if langs["rust"] {
		languageRows, rowCount := buildRustRows(all.Rust, rustLicenses)
		rows = append(rows, languageRows...)
		rowSummary = append(rowSummary, fmt.Sprintf("Rust %d crates (%d Cargo.toml lines)", rowCount, len(all.Rust)))
	}

	if langs["python"] {
		languageRows, rowCount := buildPythonRows(all.Python, usePyPI, pypiCache)
		rows = append(rows, languageRows...)
		rowSummary = append(rowSummary, fmt.Sprintf("Python %d packages (%d requirement lines)", rowCount, len(all.Python)))
	}

	if langs["node"] {
		languageRows, rowCount := buildNodeRows(all.Node, useNPM, npmCache)
		rows = append(rows, languageRows...)
		rowSummary = append(rowSummary, fmt.Sprintf("Node.js %d packages (%d pnpm lock records)", rowCount, len(all.Node)))
	}

	if langs["java"] {
		languageRows := buildJavaInventoryRows(javaDependencies)
		rows = append(rows, languageRows...)
		rowSummary = append(
			rowSummary,
			fmt.Sprintf(
				"Java %d runtime coordinates (%d components)",
				len(languageRows),
				javaComponentCount,
			),
		)
	}

	if langs["helm"] {
		languageRows, rowCount := buildHelmRows(all.Helm, helmLicenses)
		rows = append(rows, languageRows...)
		rowSummary = append(rowSummary, fmt.Sprintf("Helm %d charts (%d dependency specs)", rowCount, len(all.Helm)))
	}

	if len(rows) == 0 {
		return fmt.Errorf(
			"no dependencies discovered for language selection %q under %s",
			parsed.Language,
			repoRoot,
		)
	}
	lines := renderGroupedDependencyRows(rows)
	if err := writeMarkdown(filepath.Join(repoRoot, "dependencies.md"), header, lines); err != nil {
		return err
	}
	summary = append(summary, fmt.Sprintf("dependencies.md (%s)", strings.Join(rowSummary, "; ")))

	if len(summary) > 0 {
		fmt.Fprintf(os.Stderr, "wrote %s\n", strings.Join(summary, "; "))
	}
	return nil
}

func parseArgs(argv []string) (args, error) {
	fs := flag.NewFlagSet("collect-dependencies", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	lang := fs.String("language", "all", "")
	fs.StringVar(lang, "l", "all", "")
	if err := fs.Parse(argv); err != nil {
		return args{}, fmt.Errorf("parse args: %w", err)
	}
	switch *lang {
	case "go", "rust", "python", "node", "java", "helm", "all":
		return args{Language: *lang}, nil
	default:
		return args{}, fmt.Errorf("invalid language %q", *lang)
	}
}

func requestedLanguages(lang string) map[string]bool {
	if lang == "all" {
		return map[string]bool{"go": true, "rust": true, "python": true, "node": true, "java": true, "helm": true}
	}
	return map[string]bool{lang: true}
}

func findRepoRoot() (string, error) {
	if override := strings.TrimSpace(os.Getenv("REPO_ROOT")); override != "" {
		return override, nil
	}
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		candidate := filepath.Join(dir, "imports.yaml")
		if st, err := os.Stat(candidate); err == nil && !st.IsDir() {
			return dir, nil
		}
		// Fall back to the .git marker for the repo root. imports.yaml is
		// intentionally absent on the OSS mirror; importPathsFromManifest then
		// returns this repository root for native dependency discovery.
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("neither imports.yaml nor .git found (started from %s)", wd)
		}
		dir = parent
	}
}
